### ISSUE TITLE
Failed package remain in `emlop p` list until emerge finished

### ISSUE THREAD

**Issue by kakra** [vincentdephily/emlop#45]
I have one package currently failing to compile and install (`games-util/gamemode-9999` because ebuild updates haven't been merged yet).

If running `emlop p` after the package failed, it remains in the prediction list with its projected build time increasing until emerge ultimately finished. At least it looks like this wrong compile time isn't recorded anywhere so it won't affect future predictions.

**Comment by vincentdephily** [comment]
Thanks for the report. I think it's the same issue as #5 ?  Do you have multiple merge processes, or a single `emerge -j2 --keep-going ...` ? It's a bit tricky to get the info emlop needs (especially in the second case), but I'll take a look.

**Comment by kakra** [comment]
Yeah I found #5 before but mine is different: Only on emerge process is running.
```bash
EMERGE_DEFAULT_OPTS="--jobs=5 --load-average 8 --keep-going --usepkg --binpkg-respect-use=y --binpkg-changed-deps=y"
MAKEOPTS="-s -j12 -l10"
```

**Comment by vincentdephily** [comment]
Fixed in 0.7.0

**Comment by kakra** [comment]
Still happens in 0.7:
![image](https://github.com/vincentdephily/emlop/assets/17684/ac6e9557-8363-4a07-bd46-f15e693f9f62)
